title: Jacob Caraccilo # your name (or website title) here
logo: "/images/IMG-7417.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  College Student
  <br><br>
  Data Scientist 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
